### ISSUE TITLE
xforward stuck with frozen image when via ssh 

### ISSUE THREAD

**Issue by fxfactorial** [aarzilli/gdlv#59] opened 2022-02-19 17:23 UTC
amazing tool, thank you 

I tried using this over ssh -X forwarding against gdlv running on an aws ec2 amazon linux instance, but when the forwarded window comes up, its a frozen image of whatever was under the window at the time the window came up. I know that ssh forwarding is indeed working, because tested and xclock, xterm do come up over forwarding.

**Comment by aarzilli** [comment] 2022-02-19 18:13
This is a duplicate of https://github.com/golang/go/issues/15100 and also https://github.com/aarzilli/gdlv/issues/26. X forwarding will not work or will work but it will be unusably slow. See #26 for a workaround.

**Closed by aarzilli** 2022-02-19 18:13 UTC

**Comment by fxfactorial** [comment] 2022-02-19 21:12
gotcha, thank you for quick resp
